export const prabhupada = require('./images/prabhupada.png')
export const beadsLight = require('./images/beads-light.png')
export const vaishnavaseva = require('./images/vaishnavaseva.png')
export const arrowRightWhite = require('./images/arrow-right-white.png')
export const plusButton = require('./images/plus-button.png')
export const checkButton = require('./images/check-button.png')
export const arrowLeft = require('./images/arrow-left.png')
export const arrowRight = require('./images/arrow-right.png')
